# Generated by Django 3.1.4 on 2021-06-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_column='content')),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Content',
                'managed': True,
            },
        ),
    ]
